In [286]:
import torch
import numpy as np

### Initializing Tensor

In [287]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float32, device = device, requires_grad=True)

print(my_tensor.shape)
print(my_tensor.device)
print(my_tensor.requires_grad)
print(my_tensor.dtype)

torch.Size([2, 3])
cpu
True
torch.float32


In [288]:
x = torch.empty(size = (3, 3))
print(x)
print(x.dtype)

tensor([[-5.9737e+28,  8.3658e-43,  3.0359e-01],
        [ 7.7926e-01,  7.2484e-01,  2.7056e-01],
        [ 8.9000e-02,  1.9808e-01,  8.9079e-01]])
torch.float32


In [289]:
x = torch.zeros((3, 3))
print(x)
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [290]:
x = torch.rand((3, 3))
print(x)
print(x.dtype)

tensor([[0.7785, 0.7979, 0.3168],
        [0.2856, 0.7729, 0.5828],
        [0.9594, 0.6471, 0.6729]])
torch.float32


In [291]:
x = torch.ones((3, 3))
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [292]:
x = torch.eye(3)
print(x)
print(x.dtype)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.float32


In [293]:
x = torch.arange(start=0, end=5, step=2, dtype=torch.float32)
print(x)
print(x.dtype)

tensor([0., 2., 4.])
torch.float32


In [294]:
x = torch.linspace(start=0, end=5, steps=3)
print(x)
print(x.dtype)

tensor([0.0000, 2.5000, 5.0000])
torch.float32


In [295]:
x = x.normal_(mean=0, std=1)
print(x)
print(x.dtype)

tensor([ 0.7505, -0.6315, -0.2528])
torch.float32


In [296]:
x = torch.empty((3, 3)).uniform_(0, 1)
print(x)
print(x.dtype)

tensor([[0.0544, 0.5007, 0.1548],
        [0.3241, 0.3494, 0.7268],
        [0.2116, 0.6833, 0.3397]])
torch.float32


In [297]:
x = torch.diag(torch.tensor([1, 2, 3]))
print(x)
print(x.dtype)

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])
torch.int64


In [298]:
tensor = torch.arange(4, dtype=torch.float32)
print(tensor.bool())
print(tensor.dtype)
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
torch.float32
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [299]:
np_array = np.zeros((5, 5), dtype = np.float32)
tensor = torch.from_numpy(np_array)
print(tensor)
print(tensor.dtype)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.float32


In [300]:
np_array_back = tensor.numpy()
print(np_array_back)
print(np_array_back.dtype)
print(np_array_back.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float32
(5, 5)


In [301]:
del x

### Tensor Math and Comparison Operations

In [302]:
X = torch.tensor([1, 2, 3], dtype = torch.float32, device=device)
Y = torch.tensor([4, 5, 6], dtype = torch.float32, device=device)

z1 = torch.empty(3)
torch.add(X, Y, out=z1)
print(z1)

z2 = torch.add(X, Y)
print(z2)

z3 = X + Y
print(z3)

tensor([5., 7., 9.])
tensor([5., 7., 9.])
tensor([5., 7., 9.])


In [303]:
torch.subtract(Y, X, out=z1)
z2 = torch.subtract(Y, X)
z3 = Y - X

print(z1)
print(z2)
print(z3)

tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])


In [304]:
torch.true_divide(Y, X, out=z1)
z2 = torch.true_divide(Y, X)
z3 = Y / X

print(z1)
print(z2)
print(z3)

tensor([4.0000, 2.5000, 2.0000])
tensor([4.0000, 2.5000, 2.0000])
tensor([4.0000, 2.5000, 2.0000])


In [305]:
t = torch.zeros(3)
t.add_(X)
print(t)

tensor([1., 2., 3.])


In [306]:
z = X.pow(2)
print(z)
z = X**2
print(z)

tensor([1., 4., 9.])
tensor([1., 4., 9.])


In [307]:
print(X>1)

tensor([False,  True,  True])


In [308]:
print(X*Y)

## Dot Product
print(X.dot(Y))
print(X@Y)

tensor([ 4., 10., 18.])
tensor(32.)
tensor(32.)


In [309]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2)
print(x3)
x3 = x1.mm(x2)
print(x3)

tensor([[1.2747, 0.7423, 1.0047],
        [1.4600, 0.8258, 1.3672]])
tensor([[1.2747, 0.7423, 1.0047],
        [1.4600, 0.8258, 1.3672]])


In [310]:
matrix_exp = torch.rand((5, 5))
print(matrix_exp.matrix_power(2))

tensor([[2.1409, 1.7413, 1.1479, 1.4474, 1.5073],
        [0.8278, 1.0355, 0.4647, 1.0244, 0.3618],
        [1.6356, 1.2283, 1.0190, 1.4534, 0.8471],
        [1.4182, 1.5545, 0.9512, 1.5831, 0.7144],
        [1.6879, 1.4222, 1.1915, 1.4869, 0.8986]])


In [311]:
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))  ## 10 x 20
tensor2 = torch.rand((batch, m, p))  ## 20 x 30

out_bmm = torch.bmm(tensor1, tensor2)  ## 10 x 30

print(out_bmm.shape)

torch.Size([32, 10, 30])


In [312]:
x1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.tensor([1, 2, 3])

print(x1+x2)
print(x1-x2)
print(x1*x2)
print(x1**x2)

tensor([[2, 4, 6],
        [5, 7, 9]])
tensor([[0, 0, 0],
        [3, 3, 3]])
tensor([[ 1,  4,  9],
        [ 4, 10, 18]])
tensor([[  1,   4,  27],
        [  4,  25, 216]])


In [313]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(x.shape)

print(torch.sum(x, dim=1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
tensor([ 6, 15, 24])


In [314]:
a = torch.tensor([-2, 1, -20, 0])
abs_a = torch.abs(a)
print(abs_a)

tensor([ 2,  1, 20,  0])


In [315]:
value_max, index_max = torch.max(x, dim=1)
value_min, index_min = torch.min(x, dim=1)

print(value_max, index_max)
print(value_min, index_min)

tensor([3, 6, 9]) tensor([2, 2, 2])
tensor([1, 4, 7]) tensor([0, 0, 0])


In [316]:
z = torch.argmax(x, dim=1)
print(z)

z = torch.argmin(x, dim=1)
print(z)

tensor([2, 2, 2])
tensor([0, 0, 0])


In [317]:
print(torch.mean(x.float(), dim=1))

tensor([2., 5., 8.])


In [318]:
print(torch.eq(X, Y))

tensor([False, False, False])


In [319]:
print(torch.sort(x, dim=0, descending=True))

torch.return_types.sort(
values=tensor([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]),
indices=tensor([[2, 2, 2],
        [1, 1, 1],
        [0, 0, 0]]))


In [320]:
print(torch.clamp(x, min=2, max=8))

tensor([[2, 2, 3],
        [4, 5, 6],
        [7, 8, 8]])


In [321]:
x = torch.tensor([0, 0, 1], dtype=torch.bool)
# print(x.any())
print(torch.any(x))
print(x.all())

tensor(True)
tensor(False)


### Tensor Indexing

In [322]:
batch_size = 16
features= 25

x = torch.rand((batch_size, features))
print(x.shape)

torch.Size([16, 25])


In [323]:
## access 1st element
print(x[0].shape)
print(x[0, :].shape)

torch.Size([25])
torch.Size([25])


In [324]:
x = torch.arange(10)
indices = [2, 4, 5, 8]
print(x[indices])

tensor([2, 4, 5, 8])


In [325]:
x = torch.arange(16)
x = x.reshape(4, -1)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [326]:
rows = torch.tensor([0, 2])
cols = torch.tensor([0, 1])

print(x[rows, cols])  ## printing (0,0) & (2,1) element of x

tensor([0, 9])


In [327]:
x = torch.arange(20)

print(x[(x<2) | (x>17)])
print(x[x.remainder(2)==0])

tensor([ 0,  1, 18, 19])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [328]:
x = torch.arange(20)

y = torch.where(x>5, -x, 2*x)
print(y)

tensor([  0,   2,   4,   6,   8,  10,  -6,  -7,  -8,  -9, -10, -11, -12, -13,
        -14, -15, -16, -17, -18, -19])


In [329]:
x = torch.tensor([[1, 2, 3], [4, 5, 1], [3, 2, 6]])
print(x.unique())
print(x.ndimension())
print(x.numel()) ## count total elements

tensor([1, 2, 3, 4, 5, 6])
2
9


### Tensor Reshaping

In [330]:
x = torch.arange(9)

x = x.view(3,3)      ## only reshape contiguous matrix
print(x)
x = x.reshape(3,3)   ## can reshape both contiguous and non-contiguous matrix
print(x)
x = x.t()
print(x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [331]:
try:
    x = x.view(9)
except:
    print('error using view')
    x = x.contiguous().view(9)
    ## or try using reshape
print(x)

error using view
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [334]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [335]:
print(x1.view(-1).shape)

torch.Size([10])


In [341]:
batch = 64
z = torch.rand((batch, 2, 5))
print(z.view(batch, -1).shape)
print(z.permute(0, 2, 1).shape)

torch.Size([64, 10])
torch.Size([64, 5, 2])


In [347]:
x = torch.arange(10)

print(x.unsqueeze(dim=0).shape)
print(x.unsqueeze(dim=1).shape)
print(torch.arange(10).unsqueeze(0).unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10])


In [351]:
x = torch.arange(10)

x = x.unsqueeze(dim=0)
print(x.shape)

x = x.squeeze(0)
print(x.shape)

torch.Size([1, 10])
torch.Size([10])
